In [3]:
from pruneshift.networks import create_network
from pruneshift.datamodules import ShiftDataModule
from pruneshift.utils import safe_ckpt_load
from pruneshift.utils import load_state_dict
from pruneshift.prune_info import PruneInfo
import torch

CKPT_PATH = "/work/dlclarge2/hoffmaja-pruneshift/experiments/img100/basemodels/mnasnet_amda/checkpoint/last.ckpt"

In [5]:
net = create_network("imagenet", "mnasnet1_0", 100)

In [6]:
net = PruneInfo(net)

In [12]:
net.summary()

module   param  comp  amount    size              shape  \
0               layers.0  weight   1.0     0.0     864      (32, 3, 3, 3)   
1               layers.3  weight   1.0     0.0     288      (32, 1, 3, 3)   
2               layers.6  weight   1.0     0.0     512     (16, 32, 1, 1)   
3    layers.8.0.layers.0  weight   1.0     0.0     768     (48, 16, 1, 1)   
4    layers.8.0.layers.3  weight   1.0     0.0     432      (48, 1, 3, 3)   
5    layers.8.0.layers.6  weight   1.0     0.0    1152     (24, 48, 1, 1)   
6    layers.8.1.layers.0  weight   1.0     0.0    1728     (72, 24, 1, 1)   
7    layers.8.1.layers.3  weight   1.0     0.0     648      (72, 1, 3, 3)   
8    layers.8.1.layers.6  weight   1.0     0.0    1728     (24, 72, 1, 1)   
9    layers.8.2.layers.0  weight   1.0     0.0    1728     (72, 24, 1, 1)   
10   layers.8.2.layers.3  weight   1.0     0.0     648      (72, 1, 3, 3)   
11   layers.8.2.layers.6  weight   1.0     0.0    1728     (24, 72, 1, 1)   
12   layers.9.0.layers.0  weight   1.0     0.0    1728     (72, 24, 1, 1)   
13   layers.9.0.layers.3  weight   1.0     0.0    1800      (72, 1, 5, 5)   
14   layers.9.0.layers.6  weight   1.0     0.0    2880     (40, 72, 1, 1)   
15   layers.9.1.layers.0  weight   1.0     0.0    4800    (120, 40, 1, 1)   
16   layers.9.1.layers.3  weight   1.0     0.0    3000     (120, 1, 5, 5)   
17   layers.9.1.layers.6  weight   1.0     0.0    4800    (40, 120, 1, 1)   
18   layers.9.2.layers.0  weight   1.0     0.0    4800    (120, 40, 1, 1)   
19   layers.9.2.layers.3  weight   1.0     0.0    3000     (120, 1, 5, 5)   
20   layers.9.2.layers.6  weight   1.0     0.0    4800    (40, 120, 1, 1)   
21  layers.10.0.layers.0  weight   1.0     0.0    9600    (240, 40, 1, 1)   
22  layers.10.0.layers.3  weight   1.0     0.0    6000     (240, 1, 5, 5)   
23  layers.10.0.layers.6  weight   1.0     0.0   19200    (80, 240, 1, 1)   
24  layers.10.1.layers.0  weight   1.0     0.0   38400    (480, 80, 1, 1)   
25  layers.10.1.layers.3  weight   1.0     0.0   12000     (480, 1, 5, 5)   
26  layers.10.1.layers.6  weight   1.0     0.0   38400    (80, 480, 1, 1)   
27  layers.10.2.layers.0  weight   1.0     0.0   38400    (480, 80, 1, 1)   
28  layers.10.2.layers.3  weight   1.0     0.0   12000     (480, 1, 5, 5)   
29  layers.10.2.layers.6  weight   1.0     0.0   38400    (80, 480, 1, 1)   
30  layers.11.0.layers.0  weight   1.0     0.0   38400    (480, 80, 1, 1)   
31  layers.11.0.layers.3  weight   1.0     0.0    4320     (480, 1, 3, 3)   
32  layers.11.0.layers.6  weight   1.0     0.0   46080    (96, 480, 1, 1)   
33  layers.11.1.layers.0  weight   1.0     0.0   55296    (576, 96, 1, 1)   
34  layers.11.1.layers.3  weight   1.0     0.0    5184     (576, 1, 3, 3)   
35  layers.11.1.layers.6  weight   1.0     0.0   55296    (96, 576, 1, 1)   
36  layers.12.0.layers.0  weight   1.0     0.0   55296    (576, 96, 1, 1)   
37  layers.12.0.layers.3  weight   1.0     0.0   14400     (576, 1, 5, 5)   
38  layers.12.0.layers.6  weight   1.0     0.0  110592   (192, 576, 1, 1)   
39  layers.12.1.layers.0  weight   1.0     0.0  221184  (1152, 192, 1, 1)   
40  layers.12.1.layers.3  weight   1.0     0.0   28800    (1152, 1, 5, 5)   
41  layers.12.1.layers.6  weight   1.0     0.0  221184  (192, 1152, 1, 1)   
42  layers.12.2.layers.0  weight   1.0     0.0  221184  (1152, 192, 1, 1)   
43  layers.12.2.layers.3  weight   1.0     0.0   28800    (1152, 1, 5, 5)   
44  layers.12.2.layers.6  weight   1.0     0.0  221184  (192, 1152, 1, 1)   
45  layers.12.3.layers.0  weight   1.0     0.0  221184  (1152, 192, 1, 1)   
46  layers.12.3.layers.3  weight   1.0     0.0   28800    (1152, 1, 5, 5)   
47  layers.12.3.layers.6  weight   1.0     0.0  221184  (192, 1152, 1, 1)   
48  layers.13.0.layers.0  weight   1.0     0.0  221184  (1152, 192, 1, 1)   
49  layers.13.0.layers.3  weight   1.0     0.0   10368    (1152, 1, 3, 3)   
50  layers.13.0.layers.6  weight   1.0     0.0  368640  (320, 1152, 1, 1)   
51            

In [3]:
state_dict = torch.load(CKPT_PATH, map_location=lambda storage, device: storage)["state_dict"]

In [2]:
state_dict2 = load_state_dict(CKPT_PATH)

Found metadata


AttributeError: 'dict' object has no attribute '_metadata'

In [4]:
state_dict2._me

AttributeError: 'dict' object has no attribute '_meta_data'

In [5]:
hasattr(state_dict, "_metadata")

True

In [19]:
safe_ckpt_load(net, CKPT_PATH)

AssertionError: 

In [65]:
data = ShiftDataModule("imagenet", batch_size=128, root="/misc/scratchSSD2/datasets/ILSVRC2012-100")

In [66]:
data.setup("fit")

In [68]:
idx, x, y = next(iter(data.train_dataloader()))

In [71]:
print("True labels:")
print(y)
print("Train mode:")
net.train()
print(net(x).argmax(1))
print("Eval mode:")
net.eval()
print(net(x).argmax(1))
print("Dropout Eval mode:")
net.train()
net.network.classifier[0].train()
print(net(x).argmax(1))
print("Batch norm Eval mode:")
# net.load_state_dict(state_dict)
net.train()
for module in net.modules():
    if isinstance(module, torch.nn.BatchNorm2d):
        module.eval()
print(net(x).argmax(1))

for name, module in net.named_modules():
    if not isinstance(module, torch.nn.BatchNorm2d):
        continue
    # net.load_state_dict(state_dict)
    net.train()
    module.eval()
    print(f"Batch norm {name} Eval mode:")
    print(net(x).argmax(1))

True labels:
tensor([71, 55, 93, 88, 99,  0, 43, 53, 17, 36, 70, 83, 59, 89, 95, 37,  0, 47,
        14, 48, 54, 54, 89, 41, 39, 39, 69, 85, 51, 48, 97, 80, 39, 41, 29, 24,
        55,  8, 17, 84, 19, 26, 24, 14, 78, 18, 71, 23, 32,  3, 60, 65, 20, 42,
        55, 20, 24, 62, 16, 53, 74,  3,  8, 27, 51,  6, 64, 82, 30, 89, 85, 52,
        41, 50, 48,  2, 11, 77, 75, 33, 48, 48, 11,  3, 65, 61, 95, 36, 89, 96,
        43, 84, 44, 39,  6, 15, 46, 30, 78, 56, 17, 83,  4, 54, 85, 33, 71, 32,
        33, 58, 15, 86, 35, 49, 83, 39, 89, 80, 80, 84, 87,  3, 38, 97,  9,  7,
        57, 77])
Train mode:
tensor([71, 55, 93, 88, 99,  0, 43, 94, 18, 36, 98, 83, 59, 89, 95, 37,  0, 47,
        14, 48, 54, 54, 89, 41, 39, 39, 69, 85, 51, 48, 97, 80, 64, 41, 29, 24,
        66,  8, 17, 84, 19, 26, 33, 14, 78, 18, 71, 23, 32,  3, 41, 65, 20, 41,
        55, 20, 33, 62, 29, 77, 63,  3,  8, 27, 51,  6, 64, 82, 30, 89, 18, 52,
        41, 50, 48,  2, 11, 73, 75, 34, 48, 63, 11,  3, 65, 61, 95, 36, 89, 96

In [56]:
show_results(net, x, y)

True labels:
Train mode:
tensor([28, 79, 54, 45, 53, 86,  2, 53, 80, 60, 30, 13, 95, 24, 90, 21, 23, 56,
        86, 93, 59, 94, 44, 39, 63, 52, 53,  5, 54, 33, 97,  7])


In [28]:
pred = net(x).argmax(1)

In [29]:
pred.classifier

tensor([28, 44, 54, 45,  1, 86,  2, 57, 65, 60, 30, 13, 95, 24, 90, 21, 23, 56,
        86, 93, 59, 94, 24, 39, 63, 52, 53,  5, 54, 33, 97,  7])

In [30]:
y

tensor([99, 93, 54, 83, 69, 32,  5,  1,  4, 61, 99, 81, 12, 77,  5, 21, 93, 29,
         7, 93, 59, 76, 67, 39, 42, 39, 53,  5, 54, 29, 36, 24])

In [31]:
pred == y

tensor([False, False,  True, False, False, False, False, False, False, False,
        False, False, False, False, False,  True, False, False, False,  True,
         True, False, False,  True, False, False,  True,  True,  True, False,
        False, False])

In [47]:
net = net.train()

In [53]:
pred = net(x).argmax(1)

In [54]:
pred

tensor([28, 44, 54, 45,  1, 86,  2, 53, 80, 60, 30, 13, 68, 24, 90, 21, 23, 56,
        66, 93, 59, 94, 24, 39, 63, 52, 53, 20, 54, 33, 97,  7])

In [52]:
net.classifier[0].train()

Dropout(p=0.2, inplace=True)